---
- name: Installing golang
  ansible.builtin.dnf: 
    name: golang
    state: installed

- name: artifact download
  ansible.builtin.include_tasks:
    file: artifact_download.yml

- name: Installing Golang dependencies
  ansible.builtin.shell: go mod init dispatch ; go get ; go build
  args:
    chdir: /app

- name: systemd_setup
  ansible.builtin.include_tasks:
    file: systemd_setup.yml